# config/meta.yml

meta_product_name: "Originex"
meta_title: "Originex - Share new experiences"
meta_description: "Looking for fun and meeting new people? Join people with same interests and attend an event together or just organize one and invite them!"
meta_image: "friends-for-og-image.png" # should exist in `app/assets/images/`